### ISSUE TITLE
Question: will this work on Ventura?

### ISSUE THREAD

**Issue by edofe99** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#36]
Will the current EFI release work if I use it for a ventura fresh installation or do I have to go back to previous releases' Thank's

**Comment by 5T33Z0** [comment]
Yes, but you have to add the `AirportItlwm.kext` for Ventura included in this [zip](https://github.com/5T33Z0/Thinkpad-T490-Hackintosh-OpenCore/tree/main/Additional_Files/Slimmed_Kexts/Intel_AC-9650/itlwm/2.4.0) and adjust the Min/Max Kernel settings accordngly so that it only loads for Ventura  (Min: 22.0.0, Max: 22.9.9)
