### ISSUE TITLE
Why 256mb vram?

### ISSUE THREAD

**Issue by Acidicperson** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#43]
If I may ask, why did you choose to set graphics memory at only 256MB when it could be set all the way up to 512?
I left mine at 512 but what made me curious is that all those that installed macos on the same type of machine chose to set it at 256MB only.... Please I would love to know if I am missing something.

**Comment by 5T33Z0** [comment]
I think it's not really important what you set the VRAM in the UEFI at. Because the actually VRAM used by macOS is defined in the framebuffer patch and changes once OC is loaded. And in my config it's set to 2048 MB. VRAM is a bit of a confusing topic so maybe this helpsas am explanation: https://osxlatitude.com/forums/topic/17804-dvmtstolenmemfbmemcursormem-why-do-we-patch-these-for-broadwell-and-later/
