### ISSUE TITLE
Airplay and Continuity

### ISSUE THREAD

**Issue by Acidicperson** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#45]
For the first and second time I used this efi, I was able to sign in to iCloud and have iMessage working without any issues. But now, it signs in but iMessage doesn’t work, neither does airplay, continuity and other services except for iCloud Photos and Drive.
Do I need to tweak the smbios as you stated? 
Because I have never done that and Apple Id have always worked.
I am running Sonoma by the way

**Comment by 5T33Z0** [comment]
Well, you need all the relevant data in the PlatformInfo/Generic section as explained here: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-imessage-and-other-services-with-opencore

If that data changed since last time you have used your system, you need to verify your Apple-ID by logging in. If you are using 2-Factor-Authentification you might have to receive a verification code via SMS on your phone. You should also login to your Apple Account online to check the number of activated devices and delete duplicates.

**Comment by Acidicperson** [comment]
Exactly, what could be the problem? With same efi, for some reason, airplay worked for me on same os, but now it doesn’t

**Comment by 5T33Z0** [comment]
I don't know. You need to figure this out on your own since I use neither Airplay nor Continuity nor do I have any issues with iMessage.
