### ISSUE TITLE
Sound works- but incredibly tinny

### ISSUE THREAD

**Issue by bbgoose92** [5T33Z0/Thinkpad-T490-Hackintosh-OpenCore#5]
Hello, thank you for your work, its really made the installation quite easy.
Just wondering if pretty "tinny" sound is expected from the applealc.
Ive used the kexts,efis, etc as packaged without any changes.
You have the t490 20N3, I'm using the 20N2 variant as far as Ive seen the only differences were the default equipped screen resolution and backlit keyboard.
Same alc257 realtek audio, unless I'm just woefully misinformed
Thank you for your time.

**Comment by 5T33Z0** [comment]
On my T490 sound is okay, not great, but also not tinny. But it definitely feels less full and spacey as in Windows. That's because  under Windows, sound is enhnced by dolby digital to beef up the audio with some psycho-acoustic trickery.

I've noticed that sound is also quieter if headphones are connected during boot.

**Comment by bbgoose92** [comment]
Okay thats good to hear , thank you for your response. Dolby digital really doing some heavy lifting for these speakers on windows. Happy to know i didnt do something wrong. Thank you for the assistance.
